accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import Signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", Signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="accounts"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import global_settings
from django.utils import timezone

USER_MODEL = global_settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(default=timezone.now)
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        ExpenseCategory,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        Account,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def Signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # username = request.POST.get("username")
            # password = request.POST.get("password1")
            # user = User.objects.create_user(
            #     username=username, password=password
            # )
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    return render(request, "registration/signup.html", {"form": form})

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Receipt, ExpenseCategory, Account
from django.urls import reverse_lazy


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    # success_url= reverse_lazy("home")

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(ListView):
    model = ExpenseCategory
    template_name = "receipts/categories.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(ListView):
    model = Account
    template_name = "receipts/accounts.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/new_expense.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/new_account.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("accounts")

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            <li>
                <a href="{% url 'list_categories' %}">Expense Categories</a>
            </li>
            <li>
                <a href="{% url 'create_category' %}">Create Expense Category</a>
            </li>
            <li>
                <a href="{% url 'accounts' %}">Accounts</a>
            </li>
            <li>
                <a href="{% url 'create_account' %}">Create Account</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
            {% block extra_links %}
            {% endblock extra_links %}
        </ul>
    </nav>
    {% block content %}
    {% endblock content %}
</body>
</html>

receipts/templates/receipts/accounts.html
{% extends 'base.html' %}


{% block content %}
<main>
    <h1>My Accounts</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </tr>
        {% for account in account_list %}
            {% if account.owner == request.user %}
                <tr>
                    <th>{{ account.name }}</th>
                    <th>{{ account.number }}</th>
                    <th>{{ account.receipts.count }}</th>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
</main>
{% endblock content %}

receipts/templates/receipts/categories.html
{% extends 'base.html' %}


{% block content %}
<main>
    <h1>My Expense Categories</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
        {% for category in expensecategory_list %}
            {% if category.owner == request.user %}
                <tr>
                    <th>{{ category.name }}</th>
                    <th>{{ category.receipts.count }}</th>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
</main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}


{% block content %}
<main>
    <div>
        <h1>Create Receipt</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}


{% block content %}
<main>
    <h1>My Receipts</h1>
    <table>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
        {% for receipt in receipt_list %}
            {% if receipt.purchaser == request.user %}
                <tr>
                    <th>{{ receipt.vendor }}</th>
                    <th>{{ receipt.total }}</th>
                    <th>{{ receipt.tax }}</th>
                    <th>{{ receipt.date | date:"m-d-Y" }}</th>
                    <th>{{ receipt.category }}</th>
                    <th>{{ receipt.account }}</th>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
</main>
{% endblock content %}

receipts/templates/receipts/new_account.html
{% extends 'base.html' %}


{% block content %}
<main>
    <div>
        <h1>Create Account</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/new_expense.html
{% extends 'base.html' %}


{% block content %}
<main>
    <div>
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}